#!/bin/sh
export PYTHONPATH=/root/.local/share/uv/tools/kimi-cli/lib/python3.13/site-packages:/host-site-packages
exec /root/.local/share/uv/python/cpython-3.13.11-linux-x86_64-gnu/bin/python3.13 /root/.local/share/uv/tools/kimi-cli/bin/kimi "$@"
